### ISSUE TITLE
use the here package or add an

### ISSUE THREAD

**Issue by nuest** [sje30/munin-R#3]
I assume most participants will use RStudio. If we add an RStudio project file for each case study, things might work more smoothly for the participants. Then we can also rely on the `here` package for loading files relative to the project root (which will automatically be set to where the project file is).

_Too much magic @sje30 ?_

**Comment by sje30** [comment]
I think we keep it simple as possible for now; magic is good, but too early and it confuses people as they don't see the benefit of it (or when they work elsewhere and the magic aint there they get disappointed.)
